example/main/routes.py
from flask import Blueprint, render_template

main_bp = Blueprint(
    'main',
    __name__,
    template_folder='templates',
    static_folder='static'
)


@main_bp.route('/')
@main_bp.route('/home')
def home():
    return render_template('main/index.html')

example/main/templates/_base.html
<!DOCTYPE html>
<html lang="en">
    <!-- HEAD -->
    <head>
    <meta charset="UTF-8">
        <title>
            {% block title %}
            {% endblock %}
        </title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>

    </head>
    <!-- BODY -->
    <body>

        {% include 'navigation.html' %}

        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

example/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <!-- HEAD -->
    <head>
    <meta charset="UTF-8">
        <title>
            {% block title %}
            {% endblock %}
        </title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>

    </head>
    <!-- BODY -->
    <body>
        <!-- NAVBAR -->
        <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button
                        class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarNav"
                        aria-controls="navbarNav"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                    </ul>
                    {% if current_user.is_authenticated %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('user.logout') }}">log out</a>
                        </li>
                    </ul>
                    {% else %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('user.login') }}">sign in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('user.register') }}">sign up</a>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </nav>

        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

example/main/templates/main/index.html
{% extends '_base.html' %}
{% block title %}
    example
{% endblock %}
{% block content %}

    <!-- content goes here -->
    <h2>Hello World</h2>

{% endblock %}

example/main/templates/navigation.html
        <!-- NAVBAR -->
        <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button
                        class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarNav"
                        aria-controls="navbarNav"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                    </ul>
                    {% if current_user.is_authenticated %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('user.logout') }}">log out</a>
                        </li>
                    </ul>
                    {% else %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('user.login') }}">sign in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('user.register') }}">sign up</a>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </nav>