example/user/models.py
from flask_login import UserMixin

from example import db


class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String, nullable=False)
    email = db.Column(db.String, unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)

example/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, Length


class RegisterForm(FlaskForm):
    first_name = StringField(
        label='First Name',
        validators=[DataRequired(), Length(min=3)],
        render_kw={'placeholder': 'First Name'}
    )
    email = StringField(
        label='Email',
        validators=[DataRequired(), Email()],
        render_kw={'placeholder': 'Email'}
    )
    password = PasswordField(
        label='Password',
        validators=[DataRequired(), Length(min=7)],
        render_kw={'placeholder': 'Password'}
    )

    submit = SubmitField(
        label='sign up'
    )


class LoginForm(FlaskForm):
    email = StringField(
        label='Email',
        validators=[DataRequired(), Email()],
        render_kw={'placeholder': 'Email'}
    )
    password = PasswordField(
        label='Password',
        validators=[DataRequired(), Length(min=7)],
        render_kw={'placeholder': 'Password'}
    )

    submit = SubmitField(
        label='sign in'
    )

example/user/routes.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_user, login_required, logout_user

from example import bcrypt, db
from example.user.forms import LoginForm, RegisterForm
from example.user.models import User

user_bp = Blueprint(
    'user',
    __name__,
    template_folder='templates',
    static_folder='static',
)


@user_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('main.home'))
    return render_template('user/login.html', form=form)


@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(
            first_name=form.first_name.data,
            email=form.email.data,
            password=hashed_password
        )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('user.login'))
    return render_template('user/register.html', form=form)


@user_bp.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('user.login'))

example/user/templates/user/login.html
{% extends '_base.html' %}
{% block title %}
    sign in
{% endblock %}
{% block content %}

    <!-- content goes here -->
    <h2>sign in</h2>

    <form action="" method="POST">
        {{ form.hidden_tag() }}
        {{ form.email }}
        {{ form.password }}
        {{ form.submit }}
    </form>

    <a href="{{ url_for('user.register') }}">Don't have an account? Sign up</a>

{% endblock %}

example/user/templates/user/register.html
{% extends '_base.html' %}
{% block title %}
    sign up
{% endblock %}
{% block content %}

    <!-- content goes here -->
    <h2>sign up</h2>
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        {{ form.first_name }}
        {{ form.email }}
        {{ form.password }}
        {{ form.submit }}
    </form>
    <a href="{{ url_for('user.login') }}">Already have an account? Sign in</a>

{% endblock %}